image: node:8

stages:
  - tests
  - publish

before_script:
  - echo -e "\n"$NPMRC_REGISTRY_KEY >> $CI_PROJECT_DIR/.npmrc
  - sed -i -e '0,/react-prismazoom/s//@prismamedia\/react-prismazoom/' package.json
  # See: https://stackoverflow.com/questions/148451/how-to-use-sed-to-replace-only-the-first-occurrence-in-a-file

tests:
  stage: tests
  script:
    - npm install
    - npm run test
  tags:
    - PMD
    - STG
    - ci

publish:
  stage: publish
  only:
    - tags
  script:
    - npm install
    - npm publish --access restricted
  tags:
    - PMD
    - STG
    - ci
